name: Build Arm Application
on: workflow_dispatch
env:
  SNAP_DESTRUCTIVE_MODE: "true"
  USE_SYSTEM_FPM: "true"
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: chmod +x ./.sh/build.sh
      # - run: ./.sh/build.sh
      - uses: actions/checkout@v1
      - name: Build Server
        working-directory: ./server
        run: |
          cargo build --release
          mv ./target/release/control-center-server ../client/resources/server
      - name: Build Client
        working-directory: ./client
        run: |
          pnpm install --no-frozen-lockfile
          npx electron-vite build
      - name: Build App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building