name: Build Arm Application
on: workflow_dispatch
env:
  SNAP_DESTRUCTIVE_MODE: "true"
  USE_SYSTEM_FPM: "true"
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run build:linux
